name: Debug Build

on:
  push:
    branches:
      - debug

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn
      - name: Build in Debug Mode
        run: |
          yarn build --debug
      - name: List Files
        run: ls -alh